name: Releases
on:
  push:
    branches:
      - main
jobs:
    changelog:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: conventional Changelog action
              id: changelog
              uses: TriPSs/conventional-changelog-action@v3.17.0
              with:
                github-token: ${{ secrets.CHANGELOG_RELEASE }}

            - name: Create Release
              uses: actions/create-release@v1
              if: ${{ steps.changelog.outputs.skipped == 'true' }}
              env:
                GITHUB_TOKEN: ${{ secrets.CHANGELOG_RELEASE }}
              with:
                tag_name: ${{ steps.changelog.outputs.tag }}
                release_name: ${{ steps.changelog.outputs.tag }}
                body: ${{ steps.changelog.outputs.changelog }}
